import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
	id "org.jetbrains.kotlin.jvm" version "2.1.20"
}

def buildNumberFile = file('build.number')
def currentModVersion = project.mod_version
def buildNumber = 1

// Read previous version from a separate file to track version changes
def versionFile = file('last.version')

if (versionFile.exists()) {
	def previousVersion = versionFile.text.trim()

	if (buildNumberFile.exists()) {
		// Reset build number if mod version has changed
		if (previousVersion != currentModVersion) {
			buildNumber = 1
		} else {
			buildNumber = Integer.parseInt(buildNumberFile.text.trim()) + 1
		}
	}
}

// Write current build number
buildNumberFile.text = buildNumber.toString()

// Write current version for next comparison
versionFile.text = currentModVersion

version = "${project.mod_version}.build${buildNumber}-${project.minecraft_version}"

group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.shedaniel.me" }
	maven { url "https://maven.terraformersmc.com/" } // modmenu
	maven { url "https://api.modrinth.com/maven" }    // modrinth
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
	modRuntimeOnly "com.terraformersmc:modmenu:${project.modmenu_version}"                           // modmenu
	modRuntimeOnly "maven.modrinth:jade:${project.jade}+fabric"                                     // jade (waila)
	modImplementation "maven.modrinth:midnightlib:${project.midnightlib}-fabric"
	// REI-API (Compile-Only)
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei}"
	// REI Runtime (Runtime-Only)
	modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei}"
}

processResources {
	outputs.upToDateWhen { true }
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

// Add a task to reset the build number if needed
tasks.register('resetBuildNumber') {
	doLast {
		buildNumberFile.text = '0'
		println "Build number reset to 0"
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release.set(21)
}

tasks.withType(KotlinCompile).configureEach {
	kotlinOptions {
		jvmTarget = "21"
	}
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}