import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id 'fabric-loom' version '1.9-SNAPSHOT'
	id 'maven-publish'
	id "org.jetbrains.kotlin.jvm" version "2.0.21"
}

// Read the build number from a properties file or create it if it doesn't exist
def buildNumberFile = file('build.number')
def buildNumber = 1

if (buildNumberFile.exists()) {
	buildNumber = Integer.parseInt(buildNumberFile.text.trim()) + 1
}
buildNumberFile.text = buildNumber.toString()

// Combine version with build number
version = "${project.mod_version}.build${buildNumber}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.terraformersmc.com/" } // modmenu
	maven { url "https://api.modrinth.com/maven" }    // modrinth
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
	modRuntimeOnly "com.terraformersmc:modmenu:${project.modmenu_version}"                           // modmenu
	modRuntimeOnly "maven.modrinth:jade:${project.jade}+fabric"                                     // jade (waila)
	modImplementation "maven.modrinth:midnightlib:${project.midnightlib}-fabric"                    // midnight(config)
}

processResources {
	outputs.upToDateWhen { true }
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

// Add a task to reset the build number if needed
tasks.register('resetBuildNumber') {
	doLast {
		buildNumberFile.text = '0'
		println "Build number reset to 0"
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release.set(21)
}

tasks.withType(KotlinCompile).configureEach {
	kotlinOptions {
		jvmTarget = "21"
	}
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}