# Done to increase the memory available to gradle.
    org.gradle.jvmargs=-Xmx2G
    org.gradle.parallel=false

# Fabric Properties
# check these on https://fabricmc.net/develop
    minecraft_version=1.21.5
    yarn_mappings=1.21.5+build.1
    loader_version=0.16.10

# Mod Properties
    mod_version=0.14.2
    maven_group=de.additions
    archives_base_name=additions

# Dependencies (required)
 # https://modrinth.com/mod/fabric-language-kotlin/versions
    fabric_kotlin_version=1.13.2+kotlin.2.1.20
    # check these on https://fabricmc.net/develop
    fabric_version=0.119.5+1.21.5
#Dependencies (optional)
    # https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
    modmenu_version=14.0.0-rc.2
    # https://modrinth.com/mod/jade/versions
    jade=18.0.0
    # https://modrinth.com/mod/rei/versions
    rei=18.0.796
    # https://modrinth.com/mod/midnightlib/versions
    midnightlib=1.6.10+1.21.4