# Done to increase the memory available to gradle.
    org.gradle.jvmargs=-Xmx4G
    org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
    minecraft_version=1.21.4
    yarn_mappings=1.21.4+build.1
    loader_version=0.16.9

# Mod Properties
    mod_version=0.14.1-kotlin-alpha
    maven_group=de.additions
    archives_base_name=additions

# Dependencies (required)
    fabric_kotlin_version=1.13.0+kotlin.2.1.0
    # check these on https://fabricmc.net/develop
    fabric_version=0.110.5+1.21.4
    # https://gitlab.com/supersaiyansubtlety-group/minecraft-mods/sss_translate/-/packages
    crowdin=1.5.2+MC1.21

#Dependencies (optional)
    # https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
    modmenu_version=13.0.0-beta.1
    # https://modrinth.com/mod/jade/versions
    jade=17.0.0
    # https://modrinth.com/mod/emi/versions
    emi=1.1.18
    # https://modrinth.com/mod/midnightlib/versions
    midnightlib=1.6.6