# Done to increase the memory available to gradle.
    org.gradle.jvmargs=-Xmx4G
    org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
    minecraft_version=1.21
    yarn_mappings=1.21+build.9
    loader_version=0.15.11
# Mod Properties
    mod_version=0.14.1.21-kotlin-alpha
    maven_group=de.additions
    archives_base_name=additions

# Dependencies (required)
    fabric_kotlin_version=1.11.0+kotlin.2.0.0
    fabric_version=0.100.6+1.21
    # https://gitlab.com/supersaiyansubtlety-group/minecraft-mods/sss_translate/-/packages
    crowdin=1.5.1+MC1.21

#Dependencies (optional)
    # https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
    modmenu_version=11.0.1
    # https://modrinth.com/mod/jade/versions
    jade=15.1.4
    # https://modrinth.com/mod/emi/version
    emi=1.1.10
    #
    midnightlib=1.5.7