pluginManagement {
	Properties props = new Properties()
	file("gradle.properties").withInputStream { props.load(it) }

	plugins {
		id 'net.fabricmc.fabric-loom'               version props.loom_version
		id 'org.jetbrains.kotlin.jvm'  version props.kotlin_version
	}

	repositories {
		maven { url "https://maven.fabricmc.net/" }
		gradlePluginPortal()
	}
}

rootProject.name = "DOMAdditions"